### ISSUE TITLE
Commenting in functions?

### ISSUE THREAD

**Issue by josephdviviano** [jonmik/JNeuroSci2015#1]
Hey Jon,

Great work, looks like. Three suggestions:

1) It would be optimal if you could include your dependencies. Do you have access to community-written code you could use in place of the matlab toolboxes this depends on?

2) Your documentation at the top of your matlab code would be better placed in the README.md file.

3) Your matlab code is pretty clean and your variables are reasonably named. However it would be a lot easier to read if you restricted your code-width to 80 characters, and you sprinkled some comments throughout. 

Great work, though :)

**Comment by jonmik** [comment]
Joseph! 
Thank you for the feedback :)

The comment block at the top of the file is in accordance with the MATLAB internal help markup style for help() & doc(). See the same comment block for the answer to your query about open toolboxes.  

I strongly encourage a read through of the entire comment block, as the code itself is quite useless without comprehending the nature analysis, expected input formatting, and how to interpret the output.

Lastly, the 80 character line 'limit' is a antiquarian artifact from historically famous punch cards and terminals. While I do plan to continue improving the aesthetics of this code, I think the new suggested line length of 100-130 are much more reasonable for today's environments. I personally find the style herein more readable than the vertical style where you have one argument per line, etc.

I will endeavor to clean it up some more, while making it ever the more verbose. 

Thanks again.

**Comment by jonmik** [comment]
Hi Joseph, 
Thanks for your feedback.

I will work to clean up the code a bit and make the documentation more verbose.

I strongly encourage yourself and everyone else to read the comment block at the top of the file.
Therein you will find the answer to your first question, as long as other key information 
needed to comprehend the analysis, it's intention, layout, input, and output.

Lastly, an 80 charterer width line is historical artifact that does not lend it self to reading code imho.
More modern standards typically recommend a soft limit of 100-130 characters per a line. 
I don't enjoy excessively vertical code personally.

Thanks again,
- Jonathan.
